services:
  db:
    image: postgres:15
    container_name: workSync_db
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: workSync_app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
