FROM eclipse-temurin:17

WORKDIR /app

COPY ./*.jar app.jar
# COPY .env .env

EXPOSE 8080

ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USERNAME
ARG DB_PASSWORD
ARG JWT_SECRET
ARG KAFKA_BROKER
ARG KAFKA_ZOOKEEPER
ARG SPRING_PROFILES_ACTIVE
ARG SERVER_PORT

ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_NAME=${DB_NAME}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV KAFKA_BROKER=${KAFKA_BROKER}
ENV KAFKA_ZOOKEEPER=${KAFKA_ZOOKEEPER}
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV SERVER_PORT=${SERVER_PORT}


ENTRYPOINT ["java", "-jar", "app.jar"]
