spring:
  application:
    name: projectManager
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${username}
    password: ${password}
    url: jdbc:postgresql://localhost:5432/${dbname}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
jwt:
  secretKey: ${key}
