ALTER TABLE notifications 
DROP CONSTRAINT IF EXISTS check_notification_type;

ALTER TABLE notifications 
ADD CONSTRAINT check_notification_type 
CHECK (type IN (
    'JOIN_REQUEST', 
    'JOIN_APPROVED', 
    'JOIN_REJECTED',
    'MEMBER_REMOVED',
    'TASK_ASSIGNED',
    'TASK_CREATED',
    'TASK_DELETED',
    'TASK_STATUS_CHANGED',
    'TASK_DUE_SOON',
    'TASK_OVERDUE',
    'PROJECT_UPDATED',
    'PROJECT_STATUS_CHANGED',
    'TASK_COMMENTED',
    'MENTIONED_IN_COMMENT'
));
