ALTER TABLE users RENAME COLUMN password_hash TO password;

ALTER TABLE users ADD COLUMN username VARCHAR(50) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN name VARCHAR(100);
ALTER TABLE users ADD COLUMN bio VARCHAR(500);
ALTER TABLE users ADD COLUMN avatar_url TEXT;
ALTER TABLE users ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'user';
ALTER TABLE users DROP COLUMN enabled;
ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(100);
ALTER TABLE users ALTER COLUMN updated_at DROP DEFAULT;
